export const STREETS = [
'3, Ruta Nacional',
'1 de Mayo, Calle',
'13 de Julio, Calle',
'17 de Octubre, Calle',
'19 de Diciembre, Calle',
'2 de Abril, Calle',
'20 de Julio, Calle',
'20 de Junio, Calle',
'25 de Mayo, Calle',
'28 de Noviembre, Calle',
'9 de Julio, Calle',
'A Borghiale, Calle',
'A J Barck, Calle',
'A Mendez, Calle',
'A Vivanco, Calle',
'Abuela Paredes, Calle',
'Aconcagua, Calle',
'Adolfo Parejas Baquiano, Calle',
'Africa, Calle',
'Alberdi, Calle',
'Albert Einstein, Calle',
'Alberti, Calle',
'Alberto Sabin, Calle Doctor',
'Alberto Williams, Calle',
'Alcorta, Calle',
'Alejandro Adrian Bonini, Calle',
'Alejandro Fadul Lavaque, Calle',
'Alfonsina Storni, Calle',
'Alfredo Bernardo Nobel, Calle',
'Alicia Moreau de Justo, Calle',
'Almafuerte, Calle',
'Almirante Guillermo Brown, Calle',
'Alumno Piloto Lero Rivera, Calle',
'Alvear, Calle',
'Amado Nervo, Calle',
'Amador Gonzalez, Calle',
'America, Calle',
'Angel Carnota, Calle Doctor',
'Angel Francisco Banciella, Calle',
'Angel Sureda, Calle General',
'Angel Vicente Peñaloza, Calle General',
'Angelin Fernandez, Calle',
'Antartida Argentina, Calle',
'Antonio Alvarez Jonte, Calle',
'Antonio Balado, Calle',
'Antonio Berni, Calle',
'Antonio Berutti, Calle',
'Antonio Machado, Calle',
'Antonio Maximo Bavera, Calle Doctor',
'Antonio Rivero, Calle',
'Antonio Soto, Calle',
'Araoz de Lamadrid, Calle General',
'Arturo Fenton, Calle',
'Arturo Humberto Illia, Calle Doctor',
'Arturo Jauretche, Calle Doctor',
'Asia, Calle',
'Asturias, Avenida',
'Avellaneda, Calle',
'Ayacucho, Calle',
'Ayohuma, Calle',
'Azcuenaga, Calle',
'B M Campos, Calle',
'Bahia Agradable, Calle',
'Bahia Aguirre, Calle',
'Bahia Buen Suceso, Calle',
'Bartolome Mitre, Calle',
'Batalla Puerto Argentino, Calle',
'Bautista Mendioroz, Calle',
'Belgrano, Calle',
'Bell Graham, Calle',
'Bella Vista, Calle',
'Benigno Carro, Calle',
'Benito Perez Galdos, Calle',
'Benito Quinquela Martin, Calle',
'Bernardino Rivadavia, Calle',
'Bernardo Houssay, Calle Doctor',
'Bernardo O Higgins, Calle General',
'Bistritsky, Calle',
'Blanco Usher, Calle Intendente',
'Blas Parera, Calle',
'Blumetti, Calle',
'Bolivia, Calle',
'Bomberos Voluntarios, Calle',
'Brasil, Calle',
'Buenos Aires, Calle',
'Cabildo, Calle',
'Cabo Buen Tiempo, Calle',
'Cabo Virgenes, Calle',
'Cacique Capipe, Calle',
'Cacique Casimiro Bigua, Calle',
'Cacique Orkeke, Calle',
'Cacique Pocon, Calle',
'Cacique Rufino Ibañez, Calle',
'Cacique Yatel, Calle',
'Calafate, Calle',
'Camusu Aike, Calle',
'Cañadon Leon, Calle',
'Cañadon Salto, Calle',
'Cañadon Seco, Calle',
'Capitán de Fragata P Giachino, Calle',
'Cardenas de Vivar, Calle',
'Carlitos Chaplin, Calle',
'Carlos Beccar, Avenida Teniente',
'Carlos Gardel, Calle',
'Carlos Luis Spegazzini, Calle',
'Carlos Pellegrini, Calle',
'Caseros, Calle',
'Casimira Castro, Calle',
'Catamarca, Calle',
'Cecilia Grierson, Calle',
'Ceferino Namuncura, Calle',
'Cent de Infanteria de Marina, Calle',
'Cepeda, Calle',
'Cerro Frailes, Calle',
'Cerro Las Dos Hermanas, Calle',
'Cerro Redondo, Calle',
'Chacabuco, Calle',
'Chaco, Calle',
'Charles Darwin, Calle',
'Charlotte Fairchild, Calle',
'Chile, Calle',
'Chimen Aike, Calle',
'Chubut, Calle',
'Ciudad de Los Cesares, Calle',
'Ciudad de Necochea, Calle',
'Ciudad de Rojas, Calle',
'Ciudad del Nombre de Jesus, Calle',
'Cochabamba, Calle',
'Comandante Luis Piedrabuena, Avenida',
'Comdoro Luis Py, Calle',
'Comodoro Martin Rivadavia, Calle',
'Congreso, Calle',
'Conrado Asselborm, Calle',
'Consejal Pedro Borquez, Calle',
'Constantino Peña, Calle',
'Constituyentes, Avenida',
'Cordoba, Calle',
'Cornelio Saavedra, Calle General',
'Coronel del Castillo, Calle Teniente',
'Coronel Villegas, Calle',
'Correa Falcon, Calle',
'Corrientes, Calle',
'Costa Rica, Calle',
'Crio General Juan Angel Pirker, Calle',
'Cristobal Colon, Calle',
'Crucero General Belgrano, Calle',
'Cuba, Calle',
'Cueva de Las Manos, Calle',
'Curupayti, Calle',
'D Agustini, Calle',
'De los Inmigrantes, Avenida',
'Dean Funes, Calle',
'Defensa, Calle',
'Diaz Velez, Calle',
'Doctor Alberto Sabin, Calle',
'Doctor Angel Carnota, Calle',
'Doctor Antonio Maximo Bavera, Calle',
'Doctor Arturo Humberto Illia, Calle',
'Doctor Arturo Jauretche, Calle',
'Doctor Bernardo Houssay, Calle',
'Doctor Francisco Rene Ferrada, Calle',
'Doctor Jose Ingenieros, Calle',
'Doctor Juan Bautista Justo, Calle',
'Doctor Juan Jose Paso, Calle',
'Doctor Luis Pasteur, Calle',
'Doctor M Banic, Calle',
'Doctor M Moreno, Calle',
'Doctor Manuel Belgrano, Calle',
'Doctor Raul Scalabrini Ortiz, Calle',
'Doctor Ricardo Balbin, Avenida',
'Doctor Tomas Godoy Cruz, Calle',
'Doctor V Alsina, Calle',
'Domingo Erbieta Muñobe, Calle',
'Domingo French, Calle',
'Don Bosco, Calle',
'Dorrego, Calle',
'E Fernandez, Calle',
'Ecuador, Calle',
'El Ceibo, Calle',
'El Chalten, Calle',
'El Coiron, Calle',
'El Heraldo del Sur, Calle',
'El Notro, Calle',
'El Portezuelo, Calle',
'Elcano, Calle',
'Emilia Rodiño de Clark, Calle',
'Emilio Floreal, Calle',
'Entre Rios, Calle',
'Errazuriz, Calle',
'España, Calle',
'Estado de Israel, Calle',
'Estanislao Lopez, Calle',
'Esteban Echeverria, Calle',
'Estefania Moreno de Gay, Calle',
'Estrada, Calle',
'Europa, Calle',
'Eva Peron, Calle',
'Facon Grande, Calle',
'Facundo Quiroga, Calle',
'Falucho, Calle',
'Federico Sphur, Calle',
'Feliciano Chiclana, Calle',
'Felipe Boero, Calle',
'Felix Aldao, Calle',
'Fernando de Aragon, Calle',
'Fernando Diego Garcia, Calle',
'Feruglio, Calle',
'Fitz Roy, Calle',
'Florencio Catrihuala, Calle',
'Florentino Ameghino, Calle',
'Floro Ugarte, Calle',
'Forgas, Calle',
'Formosa, Calle',
'Fragata P Giachino, Calle Capitán de',
'Francisco Narciso de Laprida, Calle',
'Francisco Pereyra, Calle',
'Francisco Ramírez, Calle',
'Francisco Rene Ferrada, Calle Doctor',
'Francisco Vicic, Calle',
'Francisco Zucarino, Calle',
'Fray Bartolome de Las Casas, Calle',
'Fray Santa Maria de Oro, Calle',
'Gabriela Mistral, Calle',
'Gandhi, Calle',
'Garcia Lorca, Calle',
'Gendarmeria Nacional, Calle',
'General Angel Sureda, Calle',
'General Angel Vicente Peñaloza, Calle',
'General Araoz de Lamadrid, Calle',
'General Bernardo O Higgins, Calle',
'General Cornelio Saavedra, Calle',
'General Guemes, Calle',
'General Jose A Roca, Avenida Presidente',
'General Juan Felipe Ibarra, Calle',
'General Juan Lavalle, Calle',
'General Justo Jose de Urquiza, Calle',
'General Mosconi, Calle',
'General Sureda, Calle',
'German Vidal, Calle',
'Gobernador Jose Maria Moyano, Calle',
'Gobernador Juan Manuel Gregores, Avenida',
'Gobernador Lista, Calle',
'Gobernador Mayer, Calle',
'Gobernador Paradelo, Avenida',
'Gorriti, Calle',
'Guatemala, Calle',
'Guer Aike, Calle',
'Guillermo Brown, Calle Almirante',
'Gustavo Garcia Cuerva, Calle',
'Haiti, Calle',
'Heraldo del Sur, Calle El',
'Herminio Devito, Calle',
'Hernan Cortez, Calle',
'Hielos Continentales, Calle',
'Hipolito Yrigoyen, Calle',
'Ibon Noya, Calle',
'Independencia, Calle',
'Intendente Blanco Usher, Calle',
'Intendente Zumalacarregui, Calle',
'Isabel de Castilla, Calle',
'Isla Soledad, Calle',
'Islas Malvinas, Calle',
'Islas Orcadas, Calle',
'Ismael Viñas, Calle',
'Italia, Calle',
'Ituzaingo, Calle',
'J A Fernandez, Calle',
'J Bustos, Calle',
'J C Darre, Calle',
'J Castro, Calle',
'J D Rocha, Calle',
'J Fuchs, Calle',
'J Ingenieros (a), Calle',
'Jaramillo, Calle',
'John Kennedy, Calle',
'Jorge Luis Borges, Calle',
'Jorge Newbery, Calle',
'Jorge W Abalos, Calle',
'Jose A Roca, Avenida Presidente General',
'Jose Antonio Sureda, Calle',
'Jose Borquez, Calle',
'Jose Crema, Calle Padre',
'Jose Hernandez, Calle',
'Jose Honorio Ortega, Calle',
'Jose Ignacio Rucci, Calle',
'Jose Ingenieros, Calle Doctor',
'Jose Lopez Leston, Calle',
'Jose Maria Rosa, Calle',
'Jose Marmol, Calle',
'Jose Marti, Calle',
'Jose Miranda, Calle',
'Jose Ortega y Gasset, Calle',
'Jose Progreso Mata, Calle',
'Jose Susacasa, Calle',
'Juan Bautista Justo, Calle Doctor',
'Juan Carlos Berasaluce, Calle',
'Juan Carlos Castagnino, Calle',
'Juan de Garay, Calle',
'Juan Diaz de Solis, Calle',
'Juan Domingo Peron, Avenida Presidente',
'Juan Echeverria, Calle',
'Juan Emilio Riquez, Calle',
'Juan Felipe Ibarra, Calle General',
'Juan Jose Castelli, Calle',
'Juan Jose Paso, Calle Doctor',
'Juan Lavalle, Calle General',
'Juan Manuel de Rosas, Calle',
'Juan Mouesca, Calle',
'Juan Xxiii, Calle',
'Juana Azurduy de Padilla, Calle',
'Juana de Ibarbourou, Calle',
'Juana Manso, Calle',
'Jujuy, Calle',
'Julian Aguirre, Calle',
'Julio Alberto Zunino, Calle',
'Julio Ladvocat, Calle',
'Juncal, Calle',
'Junin, Calle',
'Justo Jose de Urquiza, Calle General',
'Juventud Santacruceña, Calle',
'L Cardiel, Calle',
'La Esperanza, Calle',
'La Mañana, Calle',
'La Manchuria, Calle',
'La Pampa, Calle',
'La Paz, Calle',
'La Rioja, Calle',
'Lago Argentino, Calle',
'Lago Benigno, Calle',
'Lago Burmeister, Calle',
'Lago del Desierto, Calle',
'Lago Ghio, Calle',
'Lago Nansen, Calle',
'Lago Pueyrredon, Calle',
'Lago Quiroga, Calle',
'Lago Strobel, Calle',
'Lago Tar, Calle',
'Lago Viedma, Calle',
'Laguna Azul, Calle',
'Lapataia, Calle',
'Las Buitreras, Calle',
'Las Heras, Calle',
'Las Horquetas, Calle',
'Las Lengas, Calle',
'Las Piedras, Calle',
'Lasalle, Calle',
'Laureano Garcia, Calle',
'Leandro N Alem, Calle',
'Lenzi, Calle',
'Leonardo Da Vinci, Calle',
'Leopoldo Lugones, Calle',
'Libertad, Calle',
'Lisandro de La Torre, Calle',
'Lola Mora, Calle',
'Lopez Buchardo, Calle',
'Los Alamos, Calle',
'Los Antiguos, Calle',
'Los Canillitas, Calle',
'Los Cesares, Calle Ciudad de Los',
'Los Coihues, Calle',
'Los Guanacos, Calle',
'Los Guindos, Calle',
'Los Hornos, Calle',
'los Inmigrantes, Avenida De',
'Los Moyes, Calle',
'Los Pinguinos, Calle',
'Los Pozos, Calle',
'Los Sauces, Calle',
'Luciano Carrera, Calle',
'Luis Castagnari, Calle Teniente',
'Luis Fernandez, Calle',
'Luis Jofre de Loaiza, Calle',
'Luis Pasteur, Calle Doctor',
'Luis Piedrabuena, Avenida Comandante',
'M Banic, Calle Doctor',
'M M de La Iglesia, Calle',
'M Moreno, Calle Doctor',
'Madame Curie, Calle',
'Magallanes, Calle',
'Maipu, Calle',
'Malaspina, Calle',
'Malvina Nahir Perazzo, Calle',
'Manuel Belgrano, Calle Doctor',
'Manuel Carrillo, Calle',
'Manuel Espina, Calle',
'Manuel Jesus Molina, Calle Padre',
'Manuel Rondeau, Calle',
'Marambio, Calle',
'Marcelino Alvarez, Calle',
'Marcelino Lopez, Calle',
'Maria Baron de Gutierrez, Calle',
'Mariano Muratore, Calle',
'Marta Lynch, Calle',
'Martin Rivadavia, Calle Comodoro',
'Martin Rodriguez, Calle',
'Mascarello, Calle',
'Mata Negra, Calle',
'Mata Verde, Calle',
'Matias Mackinlay, Calle',
'Mendoza, Calle',
'Mexico, Calle',
'Midleton de Grillo, Calle',
'Miguel Angel, Calle',
'Miguel de Cervantes Saavedra, Calle',
'Miguel Segovia, Calle',
'Miranday, Calle',
'Misiones, Calle',
'Monseñor Enrique Angelelli, Calle',
'Monseñor Esandi, Calle',
'Monte Aymond, Calle',
'Mujeres Pioneras, Calle',
'Munster, Calle',
'Musico Alberto Ginastera, Calle',
'N Rogolini, Calle',
'Neuquen, Calle',
'Nicolas Zuvic, Calle',
'Nieva, Calle',
'Ñire, Calle',
'Nombre de Jesus, Calle Ciudad del',
'Norberto Fernandez, Calle',
'Nuestra Señora de Fatima, Calle',
'Obrero San Jose, Calle',
'Oceania, Calle',
'Olegario Victor Andrade, Calle',
'Oliva, Calle',
'Olivia Caleta, Calle',
'Onelli, Calle',
'Oscar Smith, Calle',
'Ovejero Patagonico, Calle',
'P Gamboa de Sarmiento, Calle',
'Pablo Borelli, Calle',
'Pablo Neruda, Calle',
'Padre Jose Crema, Calle',
'Padre Manuel Jesus Molina, Calle',
'Palermo Aike, Calle',
'Panama, Calle',
'Paraguay, Calle',
'Parana, Calle',
'Parque Industrial, Avenida',
'Pascual Perez, Calle',
'Paseo de Los Arrieros, Calle',
'Pastora Baumann, Calle',
'Patagones, Calle',
'Pavon, Calle',
'Pedro Guirado, Calle',
'Pello Paredes, Calle',
'Perito F P Moreno, Calle',
'Perovsek, Calle',
'Peru, Calle',
'Petrel, Calle',
'Pico Truncado, Calle',
'Policia del Territorio, Calle',
'Policia Provincial, Calle',
'Posadas, Calle',
'Poseiro, Calle',
'Potosi, Calle',
'Prado, Calle',
'Prefectura Naval Argentina, Calle',
'Presidente General Jose A Roca, Avenida',
'Presidente Juan Domingo Peron, Avenida',
'Primera Junta, Calle',
'Prospero Palazzo, Calle',
'Provincias Unidas, Calle',
'Puerto Argentino, Calle Batalla',
'Puerto Coyle, Calle',
'Puerto de Palos, Calle',
'Puerto Deseado, Calle',
'Puerto San Julian, Calle',
'Puerto Santa Cruz, Calle',
'Pueyrredon, Calle',
'Punta Bandera, Calle',
'Punta Loyola, Calle',
'Raimundo Amestica, Calle',
'Ramon Lista, Calle',
'Ramon y Cajal, Calle',
'Raul Scalabrini Ortiz, Calle Doctor',
'Rawson, Calle',
'Reconquista, Calle',
'Ricardo Balbin, Avenida Doctor',
'Ricardo Guiraldes, Calle',
'Ricardo Rojas, Calle',
'Richieri, Calle',
'Rio Bote, Calle',
'Rio Chico, Calle',
'Rio Grande, Calle',
'Rio Negro, Calle',
'Rio Pelque, Calle',
'Rio Pinturas, Calle',
'Rio Turbio, Calle',
'Rogelio Yrurtia, Calle',
'Roldan Molina, Calle',
'Roque Saenz Peña, Calle',
'Rosario Vera Peñaloza, Calle',
'Rotary 29, Calle',
'Ruben Dario, Calle',
'Saint Exupery, Calle',
'Salta, Calle',
'Samuel Morse, Calle',
'San Juan, Calle',
'San Julian, Calle Puerto',
'San Lorenzo, Calle',
'San Luis, Calle',
'San Martin, Avenida',
'Santa Cruz, Calle Puerto',
'Santa Fe, Calle',
'Santiago de Liniers, Calle',
'Santiago del Estero, Calle',
'Sargento Cabral, Calle',
'Sarmiento, Calle',
'Servicio Penitenciario Federa, Calle',
'Silvano Picard, Calle',
'Sor Juana Ines de La Cruz, Calle',
'Spilimbergo, Calle',
'Suano, Calle',
'Suipacha, Calle',
'Tamel Aike, Calle',
'Tehuelches, Calle',
'Teniente Carlos Beccar, Avenida',
'Teniente Coronel del Castillo, Calle',
'Teniente Luis Castagnari, Calle',
'Teofilo de Loqui, Calle',
'Thierauf Horst, Calle',
'Tierra del Fuego, Calle',
'Tomas Breheney, Calle',
'Tomas Fernandez, Calle',
'Tomas Godoy Cruz, Calle Doctor',
'Tomas Luis Barberia, Calle',
'Torres, Calle',
'Tres Lagos, Calle',
'Tripulantes del Fournier, Calle',
'Tucu Tucu, Calle',
'Tucuman, Calle',
'Tur Arsenio, Calle',
'Upsala, Calle',
'V Alsina, Calle Doctor',
'Velez Sarsfield, Calle',
'Vicente Lopez y Planes, Calle',
'Victoria Ocampo, Calle',
'Vilcapugio, Calle',
'Villarino, Calle',
'Wild, Calle',
'William Hallyday, Calle',
'Williams, Calle',
'Wilson, Calle',
'Yapeyu, Calle',
'Yugoslavia, Calle',
'Zapiola, Calle',
]